[build]
command = "npm run build && (cd generator && zola build --base-url $URL)"
publish = "generator/public"
functions = "dist/api"

[build.environment]
AWS_LAMBDA_JS_RUNTIME = "nodejs12.x"
ZOLA_VERSION = "0.10.0"

[[redirects]]
    from = "/v1/*"
    to = "/.netlify/functions/:splat"
    status = 200
    force = true

[[redirects]]
    from = "/v1/whatsnewj/ja/"
    to = "/.netlify/functions/whatsnewj?q=:q"
    query = { q = ":q" }
    status = 200
    force = true
